import type { Permission, Role } from "./index.js";

export type RolePolicy = Readonly<Record<Role, readonly Permission[]>>;

/**
 * Permissions de base attribuées par rôle.
 *
 * Ces droits constituent un minimum sûr. Les droits effectifs restent limités
 * par le périmètre de l'acteur (pays, organisation, commerce, magasin ou
 * agence), les règles ABAC et les validations supplémentaires exigées par
 * l'opération.
 */
export const ROLE_PERMISSIONS: RolePolicy = {
  SUPER_ADMIN: [
    "identity.user.read",
    "identity.user.update",
    "identity.user.suspend",
    "identity.kyc.read",
    "identity.kyc.review",
    "identity.kyc.approve",
    "identity.kyc.reject",
    "identity.document.read_sensitive",
    "account.read",
    "account.freeze",
    "payment.read",
    "payment.create",
    "payment.refund",
    "payment.cancel",
    "ledger.read",
    "ledger.adjustment.initiate",
    "ledger.adjustment.approve",
    "merchant.read",
    "merchant.update",
    "merchant.employee.manage",
    "merchant.terminal.manage",
    "merchant.settlement.read",
    "merchant.settlement.configure",
    "configuration.read",
    "configuration.update",
    "feature_flag.manage",
    "fee_rule.manage",
    "limit_rule.manage",
    "partner.manage",
    "audit.read",
    "support.case.read",
    "support.case.update",
    "data.export",
    "public_service.read",
    "public_service.configure",
    "public_case.create",
    "public_case.cancel",
    "public_payment.collect",
    "public_agent.manage",
  ],
  PLATFORM_ADMIN: [
    "identity.user.read",
    "identity.user.update",
    "identity.user.suspend",
    "account.read",
    "account.freeze",
    "payment.read",
    "payment.cancel",
    "ledger.read",
    "merchant.read",
    "merchant.update",
    "merchant.terminal.manage",
    "configuration.read",
    "configuration.update",
    "feature_flag.manage",
    "fee_rule.manage",
    "limit_rule.manage",
    "partner.manage",
    "audit.read",
    "support.case.read",
    "support.case.update",
    "public_service.read",
  ],
  COMPLIANCE_OFFICER: [
    "identity.user.read",
    "identity.kyc.read",
    "identity.kyc.review",
    "identity.kyc.approve",
    "identity.kyc.reject",
    "identity.document.read_sensitive",
    "account.read",
    "account.freeze",
    "payment.read",
    "merchant.read",
    "audit.read",
    "data.export",
  ],
  RISK_ANALYST: [
    "identity.user.read",
    "identity.kyc.read",
    "account.read",
    "account.freeze",
    "payment.read",
    "ledger.read",
    "merchant.read",
    "audit.read",
    "data.export",
  ],
  FINANCE_OPERATOR: [
    "account.read",
    "payment.read",
    "payment.refund",
    "ledger.read",
    "ledger.adjustment.initiate",
    "merchant.read",
    "merchant.settlement.read",
    "data.export",
  ],
  SUPPORT_AGENT: [
    "identity.user.read",
    "account.read",
    "payment.read",
    "merchant.read",
    "support.case.read",
    "support.case.update",
  ],
  AUDITOR: [
    "identity.user.read",
    "identity.kyc.read",
    "account.read",
    "payment.read",
    "ledger.read",
    "merchant.read",
    "merchant.settlement.read",
    "configuration.read",
    "audit.read",
    "support.case.read",
    "public_service.read",
    "data.export",
  ],
  MERCHANT_OWNER: [
    "merchant.read",
    "merchant.update",
    "merchant.employee.manage",
    "merchant.terminal.manage",
    "merchant.settlement.read",
    "pos.sale.create",
    "pos.refund.create",
    "pos.shift.close",
    "support.case.read",
    "support.case.update",
  ],
  MERCHANT_MANAGER: [
    "merchant.read",
    "merchant.employee.manage",
    "merchant.terminal.manage",
    "merchant.settlement.read",
    "pos.sale.create",
    "pos.refund.create",
    "pos.shift.close",
    "support.case.read",
    "support.case.update",
  ],
  MERCHANT_CASHIER: ["merchant.read", "pos.sale.create", "pos.refund.create", "pos.shift.close"],
  PUBLIC_AGENCY_ADMIN: [
    "public_service.read",
    "public_service.configure",
    "public_case.create",
    "public_case.cancel",
    "public_payment.collect",
    "public_agent.manage",
    "audit.read",
    "data.export",
  ],
  PUBLIC_AGENT: ["public_service.read", "public_case.create", "public_payment.collect"],
  CUSTOMER: ["account.read", "payment.read", "payment.create", "support.case.read", "support.case.update"],
  SERVICE_ACCOUNT: [],
};

export function permissionsForRoles(roles: readonly Role[]): readonly Permission[] {
  return [...new Set(roles.flatMap((role) => ROLE_PERMISSIONS[role]))];
}

export function roleHasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}
